name: deploy-prd
on:
  workflow_dispatch:
    inputs:
      deploy-version:
        description: 'Version to deploy'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/lakkanan/frontend:${{ github.event.inputs.deploy-version }}
            sed -i 's/frontend:\w+/frontend:${{ github.event.inputs.deploy-version }}/g' ~/docker-compose/prd/app-compose.yml
            export COMPOSE_IGNORE_ORPHANS=True
            docker-compose -f ~/docker-compose/prd/app-compose.yml down
            docker-compose -f ~/docker-compose/prd/app-compose.yml up -d

  acceptance-testing:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "ENV_NAME=$( [ $GITHUB_REF == "refs/heads/master" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
      - name: acceptance test
        run: curl https://lakkanan.shop/ping | grep "pong" && echo $?

  security-testing:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set env
        run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/main" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV

      - name: OWASP ZAP API Scan
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://lakkanan.shop'
